spring:
  application:
    name: feature-flag-demo

io:
  getunleash:
    app-name: feature-flag-demo
    instance-id: instance 0
    api-url: http://localhost:4242/api/
    environment: development
    api-token: default:development.unleash-insecure-api-token
