spring:
  application:
    name: feature-flag-demo
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

io:
  getunleash:
    app-name: feature-flag-demo
    instance-id: instance 0
    api-url: http://localhost:4242/api/
    environment: development
    api-token: default:development.unleash-insecure-api-token

